name: "Python Quality"
description: "Install deps, run tests, lint and bandit"
inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8 ruff bandit
      shell: bash
    - name: Lint (ruff)
      run: ruff .
      shell: bash
    - name: Tests
      run: pytest -q
      shell: bash
    - name: Bandit SAST
      run: bandit -q -r . || true
      shell: bash
