name: Python CI Security

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Pytest
        run: pytest -q

  lint:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff
        run: ruff .

  sast:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Bandit
        run: |
          python -m pip install bandit
          bandit -q -r . || true

  deps-scan:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: pip-audit
        run: |
          python -m pip install pip-audit
          pip-audit -r requirements.txt || true

  container-scan:
    runs-on: ubuntu-latest
    needs: [tests, lint, sast, deps-scan]
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t local/python-app:ci .
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: local/python-app:ci
          format: table
          exit-code: 0
